# Generated by Django 3.2.14 on 2022-08-03 14:06

from django.db import migrations, models
import django.db.models.deletion


def add_user_active_type_datas(apps, schema_editor):
    try:
        from db.models import UserActiveType

        for active_type in UserActiveType._TYPES:
            UserActiveType.objects.update_or_create(
                id=active_type.value,
                name=active_type.name,
                description=active_type.label
            )
            
    except Exception as e:
        print(e)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='생성 날짜')),
            ],
        ),
        migrations.CreateModel(
            name='DefaultBaseUser',
            fields=[
                ('defaultmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.defaultmodel')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'abstract': False,
            },
            bases=('db.defaultmodel', models.Model),
        ),
        migrations.CreateModel(
            name='DefaultTypeModel',
            fields=[
                ('defaultmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.defaultmodel')),
                ('name', models.CharField(help_text='타입 이름', max_length=255)),
                ('description', models.CharField(help_text='타입에 대한 설명', max_length=511)),
            ],
            bases=('db.defaultmodel',),
        ),
        migrations.CreateModel(
            name='UserActiveType',
            fields=[
                ('defaulttypemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.defaulttypemodel')),
            ],
            bases=('db.defaulttypemodel',),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('defaultbaseuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='db.defaultbaseuser')),
                ('email', models.CharField(help_text='이메일', max_length=255, unique=True)),
                ('username', models.CharField(help_text='사용자 이름', max_length=255)),
                ('nickname', models.CharField(help_text='사용자 별명', max_length=255, null=True)),
                ('verify_code', models.CharField(help_text='사용자 인증 코드 (예: 비밀번호 초기화 인증, 이메일 인증)', max_length=127, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('active_type', models.ForeignKey(default=1, help_text='사용자 활성화 여부', on_delete=django.db.models.deletion.DO_NOTHING, to='db.useractivetype')),
            ],
            options={
                'abstract': False,
            },
            bases=('db.defaultbaseuser',),
        ),
        migrations.RunPython(add_user_active_type_datas)
    ]
