# Generated by Django 3.2.15 on 2022-08-03 18:25

from django.db import migrations, models
import django.db.models.deletion


def add_user_active_type_datas(apps, schema_editor):
    try:
        from db.models import UserActiveType

        for active_type in UserActiveType._TYPES:
            UserActiveType.objects.update_or_create(
                id=active_type.value,
                name=active_type.name,
                description=active_type.label
            )
            
    except Exception as e:
        print(e)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserActiveType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='권한명', max_length=255)),
                ('description', models.CharField(help_text='권한에 대한 설명', max_length=511)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('created', models.DateTimeField(auto_created=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(help_text='이메일', max_length=255, unique=True)),
                ('username', models.CharField(help_text='사용자 이름', max_length=255)),
                ('nickname', models.CharField(help_text='사용자 별명', max_length=255, null=True)),
                ('verify_code', models.CharField(help_text='사용자 인증 코드 (예: 비밀번호 초기화 인증, 이메일 인증)', max_length=127, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('active_type', models.ForeignKey(default=1, help_text='사용자 활성화 여부', on_delete=django.db.models.deletion.DO_NOTHING, to='db.useractivetype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(add_user_active_type_datas)
    ]
